scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'near-stakewars'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100', 'localhost:3030']